# Serve custom local error pages, falling back to shared Conductor pages.
# Comment this include in a vhost if the application should handle these itself.
error_page 401 @conductor_error_401;
error_page 403 @conductor_error_403;
error_page 404 @conductor_error_404;
error_page 500 @conductor_error_500;

location @conductor_error_401 {
    internal;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /.conductor/error_pages/401.html @conductor_error_401_shared;
}

location @conductor_error_403 {
    internal;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /.conductor/error_pages/403.html @conductor_error_403_shared;
}

location @conductor_error_404 {
    internal;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /.conductor/error_pages/404.html @conductor_error_404_shared;
}

location @conductor_error_500 {
    internal;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /.conductor/error_pages/500.html @conductor_error_500_shared;
}

location @conductor_error_401_shared {
    internal;
    root /var/conductor/error-pages;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /401.html =401;
}

location @conductor_error_403_shared {
    internal;
    root /var/conductor/error-pages;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /403.html =403;
}

location @conductor_error_404_shared {
    internal;
    root /var/conductor/error-pages;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /404.html =404;
}

location @conductor_error_500_shared {
    internal;
    root /var/conductor/error-pages;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /500.html =500;
}
