# Shared page for requests rejected by Conductor WAF rules.
# Disable (comment out) if you don't want to expose that the WAF intercepted.
error_page 406 @conductor_waf_406;

location @conductor_waf_406 {
    internal;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /.conductor/error_pages/406.html @conductor_waf_406_shared;
}

location @conductor_waf_406_shared {
    internal;
    root /var/conductor/error-pages;
    add_header Cache-Control "no-store";
    add_header X-Application-Id $conductor_application always;
    try_files /406.html =406;
}
