###############################################################
# Laravel Nginx configuration file autogenerated by Conductor #
# https://github.com/bobsta63/conductor                       #
###############################################################


# Enable this configuration block if you wish to configure SSL and force
# all HTTP traffic to the HTTPS configuraion.
##server {
##       listen         80;
##       server_name    @@DOMAIN@@;
##       return         301 https://$server_name$request_uri;
##}

server {

    # Comment this line if you wish to are switching to HTTPS
    listen          80;

    # Standard SSL configuration
    ##listen          443;
    ##ssl on;
    ##ssl_certificate /var/conductor/certificates/@@APPNAME@@.bundle.crt;
    ##ssl_certificate_key /var/conductor/certificates/@@APPNAME@@.key;
    
    # Optional (advanced) configuration settings for SSL, uncomment if needed!
    ##ssl_client_certificate /var/conductor/certificates/AlphaSSL_Root.pem;
    ##ssl_protocols  SSLv3 TLSv1 TLSv1.2;
    ##ssl_ciphers AES:HIGH:!ADH:!MD5;
    ##ssl_prefer_server_ciphers   on;

    server_name     @@DOMAIN@@;
    server_tokens   off;

    # Application path and index file settings.
    root            /var/conductor/applications/@@APPPATH@@;
    index           index.php;

    # Logging settings
    access_log      @@HLOGS@@access.log;
    error_log       @@HLOGS@@error.log;
    rewrite_log     on;

    # Additional per-application optimisations
    charset utf-8;
    client_max_body_size 32m;

    # Enable GZip by default for common files.
    include /etc/conductor/configs/common/gzip.conf;

    # Set some sensible defaults for image files etc.
    location ~* \.(png|jpg|jpeg|gif|js|css|ico)$ {
        expires 30d;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel framework specific configuration
    if (!-d $request_filename) {
        rewrite ^/(.+)/$ /$1 permanent;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~* \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass                    unix:@@SOCKET@@;
        fastcgi_index                   index.php;
        fastcgi_split_path_info         ^(.+\.php)(.*)$;
        include                         @@FASTCGIPARAMS@@;
        fastcgi_param                   SCRIPT_FILENAME $document_root$fastcgi_script_name;
         # START APPLICTION ENV VARIABLES  
        fastcgi_param   APP_ENV         @@ENVIROMENT@@;
        # END APPLICTION ENV VARIABLES
    }

    location ~ /\.ht {
        deny all;
    }

}